### ISSUE TITLE
Chybějící díly u některých pořadů

### ISSUE THREAD

**Issue by JiriVaclavik** [kodi-czsk/plugin.video.dmd-czech.novaplus#10]
Např. u seriálu Policie Modrava http://novaplus.nova.cz/porad/policie-modrava/ mi plugin v seznamu nezobrazí žádné díly, ale jenom to z části "Ukázky, reportáže a rozhovory", což zřejmě odpovídá prvnímu nalezenému `<div>.`

Mám tip na opravu. V default.py jsem si u sebe změnil řádku 101
`items = doc.find('div', 'items')`
na
`for items in doc.findAll('div', 'items'):`
a zdá se, že to pomohlo, ale nejsem si jistý, jestli to je správně řešení. Pokud ano, bude podobná úprava třeba asi i na řádce 88 a možná i jinde. Prosím vývojáře o opravu.

**Comment by lukasenkocz** [comment]
Díky. Pomohlo mi to.

**Comment by ACZ-MIRA** [comment]
U me uprava znefunkcnila cely addon. Nejprve jsem upravil radek 101, kdyz to vypisovalo chyby tak potom i radek 88. A stale chyby a Nova Plus se nespusti, vypise chybovou hlasku. Pro me zatim problem s poradem Ulice pretrvava ...

**Comment by lukasenkocz** [comment]
Taky jsem s tím zápasil. Musí se dát správné odsazení. Pak to jde. Nejsem ale programátor, takže to neumím přesně vysvětlit - nejspíš zákonitost použitého jazyka (pythoon?). Můžu poslat můj upravený soubor.

**Comment by kapitan-iglu** [comment]
Caute,
ked uz sa bude robit uprava, ktora varianta vam bude vyhovovat rep. bude pre vas pouzitelna?

1. upravit len vylistovanie vsetkych dielov tak ako navrhuje @JiriVaclavik. Vtedy sa zobrazia vsetky epizody v takom poradi, v akom su na webe. T.j. u poradu ulice by prvych 5 dielov bolo zo sekcie "ke dni otcu", potom by nasledovalo 10 dielov zo sekcie "vysielane na Nova", potom 10 dielov zo sekcie "odvysielane na Nova Gold" a nakoniec 4 diely z "exkluzivni ukazky".

2. alebo to spravit poriadne a do poradu "ulice" pridat dalsie podadresare "ke dni otcu", "nova", "nova gold" a "xkluzivni" (platilo by to pre vsetky porady a nazvy by boli totozne s nadpismi na webe).

Prva varianta moze byt coskoro, druha boh vie kedy :) Ja tento plugin nepouzivam takze musi rozhodnut lud.

@lukasenkocz ano, spravne odsadzovanie je v pythone nutnostou

**Comment by JiriVaclavik** [comment]
Jsem pro variantu 1 jako (dočasné) řešení s tím, že výhledově by třeba mohlo dojít k úpravě na variantu 2.

**Comment by ACZ-MIRA** [comment]
Ano, varianta 1 ted, varianta 2 (mnohem lepsi) klidne pozdeji, az jak vyjde cas.

**Comment by akzafira** [comment]
Trochu se trápím s úpravou dle příspěvku "JiriVaclavik" Jaké má být správně odsazení v řádku 101 a případně 88? Nebo ještě co přesně patří do cyklu `for items in doc.findAll('div', 'items'):` ? Používám PSPad.
Děkuji

**Comment by JiriVaclavik** [comment]
Myslim, že jsem u sebe měnil jenom řádku 101 a odsazení bloku pod ní. Asi nějak takhle:
```
    else:
    # druhy styl stranky s poradem
		for items in doc.findAll('div', 'items'):
			for item in items.findAll('div', 'item_container'):
				url = item.a['href'].encode('utf-8')
				if re.search('voyo.nova.cz', str(url), re.U):
					continue
				item3 = item.find('div', 'img')
				url = item3.a['href'].encode('utf-8')
				title = item3.h3.a.getText(" ").encode('utf-8')
				thumb = item3.a.img['src']
				addDir(title,__baseurl__+url,3,thumb,1)  
```

**Comment by akzafira** [comment]
Díky. A jsou tam tabulátory a nebo mezery? Stále to nejede. Nemůžeš prosím poslat/zveřejnit soubor default.py?

**Comment by JiriVaclavik** [comment]
Ok, teď jsem to zkoušel a funguje mi to:
https://gist.github.com/JiriVaclavik/6caa5a1b87ac50214ce106ab37d5b59b#file-default-py

**Comment by ACZ-MIRA** [comment]
Ja ponechal cely soubor bez zmen, pouze radek 101 pozmenil podle navodu a odsazeni zvolil - 1x Tabulator a 1x mezera (od zacatku radku).

**Comment by akzafira** [comment]
Děkuji, funguje.
