### ISSUE TITLE
Nefunkční některé pořady 

### ISSUE THREAD

**Issue by DrazekV** [kodi-czsk/plugin.video.dmd-czech.novaplus#12]
Posledních pár dnů je problémy, že nelze spustit některé programy z archivu. Například policie modrava.

**Comment by marosrojis** [comment]
Bohužel nefungují žádné pořady.

**Comment by ACZ-MIRA** [comment]
U me nefunkcni take na vsech zarizenich. Zkousel sem i starsi verze pluginu. Porad stejny problem. Zrejme nejaka novinka na strankach Novy.

**Comment by lukasenkocz** [comment]
Tady je log problému u seriálu Ulice. Podezřelé je toto:
18:01:33 T:6040   DEBUG: XFILE::CPluginDirectory::WaitOnScriptResult - waiting on the Nova Plus TV Archiv (id=6) plugin...
18:01:33 T:12976   DEBUG: Thread LanguageInvoker start, auto delete: false
[kodi.log](https://github.com/kodi-czsk/plugin.video.dmd-czech.novaplus/files/1326654/kodi.log)

**Comment by elring** [comment]
Ahoj. 

Vypadá to, že se změnila stránka, kde se sestavují parametry pro přehrávač. Podařilo se mi addon  opravit. Mám poslat Pull Request?
Případně stačí nahradit kód na řádkách 126 - 129 za tento:

```
    httpdata   = httpdata.replace("\r","").replace("\n","").replace("\t","")
                        
    configUrl = re.compile('configUrl: \'(.+?)\'').findall(httpdata)
    print 'configUrl = ' + str(configUrl[0])
                        
    parametry = re.compile('configParams: {(.+?)}').findall(httpdata)
    linkgenerator = parametry[0].replace(" ","").replace("?',","?").replace("{configUrl:'","").replace(":'","=").replace("',","&").replace("'+'","").replace("'}","").replace(",","").replace(":parseInt(","")
    print 'configParams = ' + str(linkgenerator)
    linkgenerator = str(configUrl[0]) + str(linkgenerator)

    print 'finalUrl = ' + str(linkgenerator)
    req = urllib2.Request(linkgenerator)

```

**Comment by Trottel** [comment]
@elring Dobrá práce, ale bohužel nefunguje vše. U Tvoje tvář... jdou přehrát kratší videa, ale celý díl (4. díl z 23.9.) přehrát nejde.

**Comment by marosrojis** [comment]
Díky. Modrava taky nejde přehrát, jinak zbytek funguje parádně.

**Comment by elring** [comment]
U tvoje tvář... mi ten 4. díl nejde přehrát ani přímo na webu, takže to vypadá spíš na problém serveru. Nebo jde to někomu přehrát?

U Modravy přehrání dílu z 17.9.2017 normálně funguje i v Kodi. Nejde přehrát Modrava II - 2. díl, ale to je patrně jen odkaz na voyo, vůbec to není odkaz na konkrétní díl. Takže by se spíš vůbec neměl nabízet k přehrání...

**Comment by Trottel** [comment]
Máš pravdu, ani na webu to nejde, takže chyba je na jejich straně.
