### ISSUE TITLE
Nefunkční plugin

### ISSUE THREAD

**Issue by marosrojis** [kodi-czsk/plugin.video.dmd-czech.novaplus#16]
Po otevření pluginu nefunguje ani jedna položka menu. Měl by někdo nápad, jak to opravit?

V logu je následující:

`12:58:41.164 T:1713369856   ERROR: EXCEPTION: Non-Existent Control 300
12:58:42.969 T:1477440256 WARNING: CSkinInfo: failed to load skin settings
12:58:53.939 T:1925556736   ERROR: Control 52 in window 10025 has been asked to focus, but it can't
12:59:16.325 T:1485828864   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'NoneType' object has no attribute 'find'
                                            Traceback (most recent call last):
                                              File "/home/osmc/.kodi/addons/plugin.video.dmd-czech.novaplus/default.py", line 230, in <module>
                                                NEW(url,page)
                                              File "/home/osmc/.kodi/addons/plugin.video.dmd-czech.novaplus/default.py", line 45, in NEW
                                                items = items.find('div', 'items')
                                            AttributeError: 'NoneType' object has no attribute 'find'
                                            -->End of Python script error report<--
12:59:16.486 T:1925556736   ERROR: GetDirectory - Error getting plugin://plugin.video.dmd-czech.novaplus/?mode=6&name=Nejsledovan%c4%9bj%c5%a1%c3%ad&page=1&url=http%3a%2f%2fnovaplus.nova.cz
12:59:16.487 T:1925556736   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.dmd-czech.novaplus/?mode=6&name=Nejsledovan%c4%9bj%c5%a1%c3%ad&page=1&url=http%3a%2f%2fnovaplus.nova.cz) failed
`

**Comment by elring** [comment]
Ahoj. 
Vypadá to, že jsou komplet předělané stránky.
Zkusím plugin upravit, ale chvilku to potrvá (už mi něco relativně funguje, zbývají ještě náhledy apod.)...

**Comment by elring** [comment]
Testovací oprava je https://github.com/elring/plugin.video.dmd-czech.novaplus/tree/fix2018 - archiv ke stažení na https://codeload.github.com/elring/plugin.video.dmd-czech.novaplus/zip/fix2018

Mělo by fungovat snad vše (zatím jsem narazi jen na pořad Autohlídka, který je v nějakém zajímavém formátu 'dash'). Na stránkách se změnilo úplně všechno, tak dejte vědět, jestli opravený plugin funguje.

**Comment by marosrojis** [comment]
Super funguje, díky! :)

**Comment by akzafira** [comment]
Děkuji vřele.

**Comment by RivieraKid22** [comment]
Zase to šlape - díky moc!

**Comment by wagi-cb** [comment]
Za moji zenu moc diky ze si elring nasel cas a dal to zas do kupy.
Ucta ti.

**Comment by marosrojis** [comment]
Ještě jsem narazil na menší problém. U některých pořadů jsou zobrazeny jednotlivé díly pouze ze seznamu pod videem, ale na stránce je ještě nadpis Celé epizody, kde jsou obsaženy další díly.

Např. u seriálu [Ordinace v růžové zahradě 2](https://novaplus.nova.cz/porad/ordinace-v-ruzove-zahrade-2/) je pod videem seznam dílů 468, 467, atd. Dále se ale pod nadpisem Celé epizody nacházejí další nejnovější díly tohoto seriálů (830., 829. díl).

Až budeš mít čas @elring, mohl by ses na to prosím tě podívat?

**Comment by elring** [comment]
Nevšiml jsem si, že seznamy dílů jsou po každé jiné...
Kouknu na to, ale až příští týden.

**Comment by elring** [comment]
Koukám na to a přijde mi, že seznamy pod videem a nadpisem "Celé epizody" jsou za normálních okolností stejné. 
Jiné díly jsou tam jen v případě, že se na webu rozklikne nějaký díl z odkazu "Celé epizody na Nova Gold"... Pak se pod videem zobrazují staré díly a pod nadpisem pak nové díly. To se ale doplňku vlastně netýká...

Co by možná mělo smysl - přidat do seznamu videí i díly z nadpisu "Celé epizody na Nova Gold", případně "Bonusy"... Na stránce se sice zobrazují jen 3 díly, ale v kódu stránky je jich více.

**Comment by marosrojis** [comment]
Teď koukám na stránku Ordinace v růžové zahradě a skutečně se v seznamu vedle videa objevují nyní poslední díly z televize.
Možná bych navrhoval udělat to, že si získáš všechny videa ze stránky (jen celé epizody) a ty pak zobrazit k přehrání. S tím že se můžou nějaká videa zobrazit na stránce vícekrát.

Ale nevím jestli je u tohoto debilního seriálu toho chování unikátní nebo to je u všech.

Zkus popřemýšlet prosím tě, jestli by ti dávalo smysl to, co jsem navrh.

**Comment by elring** [comment]
Zkus https://github.com/elring/plugin.video.dmd-czech.novaplus/archive/fix2018gold.zip - ke klasickým epizodám jsem přidal ještě díly z nadpisů Nova Gold a Bonusy. Tím by to mělo být komplet. Minimálně u Ulice a Ordinace to funguje pěkně.

**Comment by marosrojis** [comment]
Paráda super! Díky moc!

**Comment by boddie2** [comment]
@elring, upravoval jsem tvuj plugin pro Enigma2. V seznamu pod videem uz ted opravdu byva to same, co v cele epizody, ale obcas i neco navic a zas ne vzdy pod necim oddil Cele epizody nebo Cele dily je. V enigme jsem to zatim udelal tak, ze pokud jde nekdo pres odkaz Serialy a porady, tak to pak hleda pod danym poradem prave sekci Cele *, kdyz nenajde, tak to pouzije seznam vedle videa.
Pres jine odkazy se pouzije seznam vedle videa. To jen tak na doplneni, diky za upravy pluginu ;)

**Comment by E000001** [comment]
opraveno, diky. zaviram.
