### ISSUE TITLE
Nefunkční plugin - změna playeru na stránkách

### ISSUE THREAD

**Issue by 72ka** [kodi-czsk/plugin.video.dmd-czech.novaplus#19]
Ahoj,

plugin nefunguje, začal jsem se na to dívat abych udělal opravu. Nemám ale bohužel už více času, takže moje poznatky, kdyby někdo chtěl opravit místo mně:

Novaplus změnila přehrávání na mpg- dash, což jsem zjistil Kodi už umí pomocí InputMediaStream, lze aktivovat v nastavení Kodi. Získání adresy na .mpd soubor mám hotový, teď jsem narazil na licenční server, bude potřeba podstrčit klíč, zde jsem zatím zůstal dál nemám čas.

**Comment by elring** [comment]
U jakého pořadu to používá mpg dash? Když jsem doplněk v září upravoval, tak takový pořad jsem našel jen jeden - Autohlídka. Mpg dash jsem zkoumal, načíst a připravit mpd mi fungovalo, ale nevěděl jsem jak vygenerovat ten klíč. To ale do budoucna.

V tuto chvíli mi to přijde jen jako malá úprava kódu stránek. Stačí v doplňku nahradit kolem řádky 162 "bitrates" za "src".
Starý kód: `bitrates = re.compile('bitrates = {(.+?)\[(.+?)\]').findall(httpdata);`
Nový kód: `bitrates = re.compile('src = {(.+?)\[(.+?)\]').findall(httpdata);`

Během dneška/zítřka připravím opravený doplněk.

**Comment by 72ka** [comment]
Fakt? Nééééé :) já jsem dostal jen nahlášeno že nejde novaplus a vše zkouším na autohlídce :))) to snad není možný, díky!

**Comment by 72ka** [comment]
BTW jinak ten klíč tam je v jednom skriptu, to už mi chodí, dá se dát jako parametr do inpustreamu. Bohužel jsem skončil na tom, že mám Windows 64 verzi a DRM knihovnu videwine mi to prostě nenačte a na tom jsem skončil.

**Comment by elring** [comment]
Já to zkoušel na Linuxu - postup, který jsem našel bylo videwine si zkopírovat z Google Chrome a odkázat se na něj... Jen ten klíč mi nějak nefungoval, ale pak jsem to vzdal, když se to týkalo jen jednoho pořadu. Myslím, že nás do ale do budoucna nemine :-)

**Comment by 72ka** [comment]
Asi nemine.. docela mě to děsí, protože jinak provozuju Kodi na arm s905 a tam vůbec nevím zda DRM funguje. No nic, děkuju, zachránil jste mi manželství, žena nemohla koukat na Ulici  :)

**Comment by elring** [comment]
Opraveno - doplněk se automaticky aktualizuje po začlenění Pull Requestu, případně je možné si doplněk ručně stáhnout - https://github.com/elring/plugin.video.dmd-czech.novaplus/archive/master.zip

**Comment by E000001** [comment]
Díky za opravu, pull request jsem zaclenil do repo ;)
