### ISSUE TITLE
MasterChef Česko

### ISSUE THREAD

**Issue by ondra598** [kodi-czsk/plugin.video.dmd-czech.novaplus#22]
Dobrý den, chtěl bych nahlásit, že pořad MasterChef Česko nefunguje v doplňku Novaplus. Nezobrazují se žádná videa. Předem děkuji

**Comment by elring** [comment]
Předběžně opravenou verzi mám na https://github.com/elring/plugin.video.dmd-czech.novaplus/archive/master.zip - MasterChef nedodržuje obvyklé nadpisy, takže prostě do seznamu dílů pořadu hodím pod sebe všechna videa bez ohledu na to, v jaké jsou kategorii (Nova Gold apod.). Je v tom trochu zmatek, ale snad to nevadí :-)
