### ISSUE TITLE
Nedostupnost nových dílů (od 3622)

### ISSUE THREAD

**Issue by lukasenkocz** [kodi-czsk/plugin.video.dmd-czech.novaplus#23]

**Comment by marosrojis** [comment]
Potvrzuji nedostupnost nových dílů, přitom na novaplus díly jsou.

Měl by někdo prosím chvilku najít, kde by mohla být chyba? Díky :)

**Comment by Rambotnik87** [comment]
Taky se pridavam, asi doslo zase k prejmenovani, dily na webu jsou. Diky

**Comment by elring** [comment]
Co vám přesně nefunguje - 3622 je Ulice? Ta mi funguje, ale používám o něco novější verzi - nějak jsem ji zapomněl poslat do oficiálního větve. Zkuste ji použít také - https://github.com/elring/plugin.video.dmd-czech.novaplus/archive/master.zip - pokud to bude ok, pošlu to dál :-)

**Comment by lukasenkocz** [comment]
Tak to bohužel nepomohlo. Ke 4 dílům (3629-3632) se přidal Vánoční speciál 2018, ale nejnovější díl 3633 z horní části stránky chybí https://novaplus.nova.cz/porad/ulice. Dnes ráno (14.3.2019) jde tedy o díl 3633, ale zítra ráno to bude zase o díl posunuté (tedy 3634)...

**Comment by elring** [comment]
Ahaaa :-) Odkaz ze seznamu pořadů nově vede přímo na nejnovější díl a v seznamu pod ním tento díl není. Zrušil jsem tento krok i v doplňku - rovnou se zobrazí výběr rozlišení a pod ním odkazy na další díly. Zkuste to - https://github.com/elring/plugin.video.dmd-czech.novaplus/archive/master.zip

**Comment by Lucky0005** [comment]
S posledním updatem zde postnutym, je malé zlepšení protože
 v sekci "Seriály a pořady" najdu třeba u výměny manželek jenom poslední díl kde je výběr v různých rozlišeních. Totéž mám v top pořady. Ostatní díly tu nejsou.

Jinak tyto sekce jsou prázdné 
Poslední epizody
Nova Plus originals
Doporučujeme

**Comment by elring** [comment]
Sekce:
- Poslední epizody - na webu přejmenovány na Poslední díly => opraveno
- Nova Plus Originals - zrušeno na webu => zrušeno i v doplňku
- Doporučujeme => opraveno
- Nejsledovanější => opraveno

Výměna manželek - ostatní díly jsou pouze na Voyo (placené?).

**Comment by Lucky0005** [comment]
Je někde aktualizovány doplněk ke stažení  s těmi úpravami co teď zmiňuješ?

**Comment by elring** [comment]
Jak jsem psal - https://github.com/elring/plugin.video.dmd-czech.novaplus/archive/master.zip

**Comment by Rambotnik87** [comment]
Aha ja ti zkousel pres aktualizaci v addonu, proto mi to neslo.

Dne čt 14. 3. 2019 16:03 uživatel Elring <notifications@github.com> napsal:

**Comment by elring** [comment]
Tam to bude, až to odladíme. Nemůžu to tam sám nahrát, musím udělat PR (pull request, žádost), kterou musí někdo schválit, změny začlenit a vydat novou verzi :-)

**Comment by Lucky0005** [comment]
Každopádně s tím přesouváním straších dílů na voyo to zabili, podle mě to časem přejde všechno na voyo a za 💰

**Comment by Rambotnik87** [comment]
To chapu, diky za snahu.

Dne čt 14. 3. 2019 16:13 uživatel Elring <notifications@github.com> napsal:

**Comment by lukasenkocz** [comment]
Za mne je ta oprava OK. Díky.

**Comment by E000001** [comment]
@elring Zkoušel jsem to a jede to. Uděláš PR? Následně schválím. Díky

**Comment by kallenp** [comment]
Kdy bude schváleno a dostupné v oficiální aktualizaci ? Děkuji

**Comment by E000001** [comment]
schváleno, díky
