### ISSUE TITLE
Nefunkčnost některých pořadů

### ISSUE THREAD

**Issue by marosrojis** [kodi-czsk/plugin.video.dmd-czech.novaplus#25]
V aktuální verzi bohužel přestalo fungovat přehrání určitých pořadů - např. Kameňák nefunguje (viz log). Zajímavé, že tento pořad ještě minulý týden fungoval.

Mohl by se na to prosím někdo podívat? Děkuji.

`10:04:16.596 T:10252   ERROR: XFILE::CDirectory::GetDirectory - Error getting
10:04:38.392 T:23548   ERROR: Previous line repeats 6 times.
10:04:38.392 T:23548   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: 'NoneType' object has no attribute '__getitem__'
                                            Traceback (most recent call last):
                                              File "C:\Users\marek.rojik\AppData\Roaming\Kodi\addons\plugin.video.dmd-czech.novaplus\default.py", line 256, in <module>
                                                VIDEOLINK(url,page)
                                              File "C:\Users\marek.rojik\AppData\Roaming\Kodi\addons\plugin.video.dmd-czech.novaplus\default.py", line 123, in VIDEOLINK
                                                url = main.find('iframe')['src']
                                            TypeError: 'NoneType' object has no attribute '__getitem__'
                                            -->End of Python script error report<--
10:04:38.419 T:7408   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.dmd-czech.novaplus/?mode=2&name=Kame%c5%88%c3%a1k&page=1&url=https%3a%2f%2fnovaplus.nova.cz%2fporad%2fkamenak
10:04:38.420 T:7408   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.dmd-czech.novaplus/?mode=2&name=Kame%c5%88%c3%a1k&page=1&url=https%3a%2f%2fnovaplus.nova.cz%2fporad%2fkamenak) failed
10:04:41.965 T:11844   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'NoneType' object has no attribute 'getText'
                                            Traceback (most recent call last):
                                              File "C:\Users\marek.rojik\AppData\Roaming\Kodi\addons\plugin.video.dmd-czech.novaplus\default.py", line 256, in <module>
                                                VIDEOLINK(url,page)
                                              File "C:\Users\marek.rojik\AppData\Roaming\Kodi\addons\plugin.video.dmd-czech.novaplus\default.py", line 119, in VIDEOLINK
                                                desc = article.find('div', 'e-description').getText(" ").encode('utf-8')
                                            AttributeError: 'NoneType' object has no attribute 'getText'
                                            -->End of Python script error report<--`

**Comment by elring** [comment]
Mně to normálně funguje (zkoušel jsem Kameňák - 6. díl)... Podle chyby to nenašlo iframe s videem. Možná momentální problém stránek?

**Comment by marosrojis** [comment]
Potvrzuji, asi momentální chyba stránek. Díky za ochotu :)

**Comment by Lucky0005** [comment]
U mě aktuálně nefunguje sekce "seriály a pořady"

**Comment by elring** [comment]
Už je to opraveno, čekám na zveřejnění opravy. Případně je možné stáhnout opravený doplněk na https://github.com/elring/plugin.video.dmd-czech.novaplus/archive/master.zip

**Comment by Lucky0005** [comment]
Díky, funguje!
