### ISSUE TITLE
Nabízí se jen jediný díl

### ISSUE THREAD

**Issue by lukasenkocz** [kodi-czsk/plugin.video.dmd-czech.novaplus#30]
Aktuálně se nabízí jen jediný díl - např. u seriálu Ulice. Přitom na stránkách je jich na výběr více. Nejspíš zase něco změnili... Díky za případnou opravu.

**Comment by Rambotnik87** [comment]
taky se přidávám s prosbou a díky za případnou opravu

**Comment by elring** [comment]
Ahoj, zkuste otestovat opravu na https://github.com/elring/plugin.video.dmd-czech.novaplus/archive/master.zip

**Comment by JSkolnik** [comment]
> Ahoj, zkuste otestovat opravu na https://github.com/elring/plugin.video.dmd-czech.novaplus/archive/master.zip

Tato verze funguje. Díky.

**Comment by marosrojis** [comment]
> Ahoj, zkuste otestovat opravu na https://github.com/elring/plugin.video.dmd-czech.novaplus/archive/master.zip

funguje, díky moc :)

**Comment by lukasenkocz** [comment]
Je to OK. Uzavírám.
