### ISSUE TITLE
Linux ?

### ISSUE THREAD

**Issue by jwkk** [kodi-czsk/plugin.video.dmd-czech.novaplus#4]
Please help or advice.
I do not know why, but it does not work on Linux Kodibuntu Jarvis (latest version).
On Windows works fine even on Krypton.
Thank you!

**Comment by jose1711** [comment]
with jarvis on arch linux everything's working fine. maybe you should add debuglog

**Comment by kapitan-iglu** [comment]
@jwkk have you still this issue? If not I'll close it.
