### ISSUE TITLE
Chyba skriptu: Nova Plus TV Archiv. PythonToCppException

### ISSUE THREAD

**Issue by tomasvrbka** [kodi-czsk/plugin.video.dmd-czech.novaplus#5]
Nelze přehrát žádné video. Někdy dělá občas teď už nejde několik hodin v kuse. Restart nepomůže. Logy:
http://kspi.cz/temp/novaplus.zip

**Comment by Marduke** [comment]
tu samou chybu mi to hlasilo taky, tak jsem se v tom hrabal a jako quickfix staci pridat # na zacatek radku 85

**Comment by Marduke** [comment]
[plugin.video.dmd-czech.novaplus-1.0.6a.zip](https://github.com/kodi-czsk/plugin.video.dmd-czech.novaplus/files/243462/plugin.video.dmd-czech.novaplus-1.0.6a.zip)
 tady je cely plugin oznaceny jako 1.0.6a

**Comment by Marduke** [comment]
vyzkouseno na pc ve verzi 16 a adnoird tabletu na verzi 16.1

**Comment by Marduke** [comment]
[plugin.video.dmd-czech.novaplus-1.0.6b.zip](https://github.com/kodi-czsk/plugin.video.dmd-czech.novaplus/files/243471/plugin.video.dmd-czech.novaplus-1.0.6b.zip)

tak predtim to byl opravdu quickfix , ukazovala to pouze posledni dil, ted uz to ukazuje vsechno

**Comment by Dimensionone** [comment]
Super funguje, testované na koni 16 pre android, ďakujem

**Comment by 72ka** [comment]
Ahoj všem, udělal jsem pull request. Je tam opravené přehrávání všech pořadů a pár vylepšení. Tak pevně věřím v zařazení. Díky.

**Comment by kapitan-iglu** [comment]
Vyriesene mergnutim #6
