### ISSUE TITLE
nejde prehrať

### ISSUE THREAD

**Issue by bodyguardroman** [kodi-czsk/plugin.video.dmd-czech.novaplus#7]
,pri pokuse o prehratie napise:zlyhalo prehravanie.
Pravdepodobne nieco menili na webe,preto to nejde...

**Comment by Marduke** [comment]
potvrzuji, nelze prehrat nic jak v androidu tak na LibreElecu tak ve windows 10

**Comment by Fighter158** [comment]
Potvrzuji, už pár dní nefunguje.

**Comment by kmarty** [comment]
V def VIDEOLINK, kousek pod radkou:
`#Dolovani rtmp adresy z configu`
 si zakomentujte radky:
`
tcurlandplaypath = rtmp_url.replace("/&"," playpath=").replace("rtmp://"," tcUrl=rtmp://")
`
a
`
rtmp_url = rtmp_url+tcurlandplaypath`

**Comment by marosrojis** [comment]
Díky funguje.

**Comment by Bartyx** [comment]
Bylo by možné vydat opravenou verzi? Na AndroidTV se mi velmi špatně upravuje jakýkoli soubor. Děkuji.

**Comment by ACZ-MIRA** [comment]
Uprava v pohode, plugin je opet funkcni. Parada diky za info.

**Comment by jagrs** [comment]
Také se přimlouvám za novou verzi.., díky.

**Comment by 72ka** [comment]
Opravil jsem to paralelně s vámi, bohužel jsem se nepodíval dřív sem. Ale je tam pull request pro opravu. Prosím o zařazení.

**Comment by Bartyx** [comment]
72ka díky za Pull. Vypadá to, že to tady nikdo nezařadí, takže budeme muset použít fork. 
Díky.

**Comment by kapitan-iglu** [comment]
Dajte prosim chalanom nejaky cas nech to skontroluju. Ked sa nikto neprihlasi tak to mergnem. 
@E000001 hm?
