### ISSUE TITLE
Seriál Ulice - chybí díly

### ISSUE THREAD

**Issue by lukasenkocz** [kodi-czsk/plugin.video.dmd-czech.novaplus#9]
V seriálu Ulice nejsou zobrazeny všechny díly. Na výběr jsou nějaké hodně staré a chybí poslední epizody.

**Comment by ACZ-MIRA** [comment]
Stejny problem, dily bud chybi nebo jsou pohazene. Deje se pouze u serialu Ulice. Pouzivam Kodi 14 na Linuxu. A aktualni verzi addonu 1.0.8

**Comment by lukasenkocz** [comment]
Problém je asi v tom, že na stránku ulice http://novaplus.nova.cz/porad/ulice/ přidali jako první část s díly ke dni otců (marketing Březňák) a právě tyto díly se zobrazují v doplňku. Je možné to opravit?

**Comment by JiriVaclavik** [comment]
Vypsal jsem nové issue s návrhem na potenciální řešení - viz #10.

**Comment by lukasenkocz** [comment]
Řešeno jiným issue.
